version: '2'
services:

  redis:
    image: redis:3-alpine
    container_name: pylon-dev-redis
    command: redis-server --appendonly yes
    ports:
      - "6380:6379"
    volumes:
      - ".data/redis:/data"

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: pylon-dev-zk
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:0.9.0.1
    container_name: pylon-dev-kafka
    ports:
      - "9092:9092"
    links:
      - zookeeper:zk 
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      KAFKA_CREATE_TOPICS: PylonWL:1:1
      KAFKA_ADVERTISED_HOST_NAME: 192.168.59.103
      KAFKA_ZOOKEEPER_CONNECT: zk:2181